import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import api from '../services/api';

export default function StudentDetails() {
    const { studentId } = useParams();
    const navigate = useNavigate();
    const [student, setStudent] = useState<any>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadStudent();
    }, [studentId]);

    async function loadStudent() {
        try {
            const res = await api.get(`/students/${studentId}`);
            setStudent(res.data);
        } catch (error) {
            console.error('Failed to load student', error);
        } finally {
            setLoading(false);
        }
    }

    async function startAssessment() {
        // Create a new assessment session
        try {
            // Assessment ID often generated by backend
            // For now, we'll create one or assume backend returns it
            // Let's assume we post to create an assessment
            // But checking our routes, we might not have a direct CREATE assessment endpoint handy in the prompt context?
            // Actually usually we might just generate a UUID frontend side or call an endpoint.
            // Let's try to navigate to a new assessment ID (using random UUID for now or check if we need to create it)
            // Just basic unique ID for demo
            const newAssessmentId = crypto.randomUUID();
            navigate(`/students/${studentId}/assessment/${newAssessmentId}`);
        } catch (e) {
            console.error(e);
        }
    }

    if (loading) return <div>Loading...</div>;
    if (!student) return <div>Student not found</div>;

    return (
        <div className="max-w-7xl mx-auto px-4 py-6">
            <button onClick={() => navigate(-1)} className="text-blue-600 mb-4">&larr; Back</button>

            <div className="bg-white shadow rounded-lg p-6">
                <div className="flex justify-between items-start">
                    <div>
                        <h1 className="text-3xl font-bold text-gray-900">{student.name}</h1>
                        <p className="text-gray-500">Student ID: {student.id}</p>
                    </div>
                    <button
                        onClick={startAssessment}
                        className="bg-indigo-600 text-white px-6 py-2 rounded-lg hover:bg-indigo-700 transition"
                    >
                        Start New Assessment
                    </button>
                </div>

                <div className="mt-8 grid grid-cols-3 gap-6">
                    <div className="bg-gray-50 p-4 rounded">
                        <span className="text-gray-500 text-sm">Age</span>
                        <p className="text-xl font-semibold">{student.age}</p>
                    </div>
                    <div className="bg-gray-50 p-4 rounded">
                        <span className="text-gray-500 text-sm">Grade</span>
                        <p className="text-xl font-semibold">{student.grade}</p>
                    </div>
                    <div className="bg-gray-50 p-4 rounded">
                        <span className="text-gray-500 text-sm">Screening Status</span>
                        <p className="text-xl font-semibold capitalize">{student.screeningStatus || 'Pending'}</p>
                    </div>
                </div>

                {/* Future: Assessment History List */}
                <div className="mt-8">
                    <h2 className="text-xl font-bold mb-4">Assessment History</h2>
                    <p className="text-gray-500 italic">No past assessments found.</p>
                </div>
            </div>
        </div>
    );
}
